# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f62520b4e2754a09105e6c6f62fb0aceaa49d75f01cc1b877ee283e64147ae04aca5dbd8c594a934bff8ff7d23559c4bb8a87a0a798babacb0d5268dd92aa52d

test:
  secret_key_base: 467aafab18e92f33976de67212d66572d3575b09b99100e16e5d670f14f9f1562630da04f3d4a4e351fb2dfe4aeaaca788f3ed3e542c5524cec1a92015e95294

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: f62520b4e2754a09105e6c6f62fb0aceaa49d75f01cc1b877ee283e64147ae04aca5dbd8c594a934bff8ff7d23559c4bb8a87a0a798babacb0d5268dd92aa52d
